### ISSUE TITLE
[bug] Can't install with go's install command

### ISSUE THREAD

**Issue by Muskra** [p0dalirius/goopts#2]
Simple as issue is named, i did the following to install the lib on computer:

`go install github.com/p0dalirius/goopts.git@latest`

This don't seems to work at the moment.

Great library tho, saved me a lot of hassles. I hate using cobra and native flags.

**Comment by p0dalirius** [comment]
Hi,

Thank you for your feedback

With your command i get a syntax error:
```
$ go install github.com/p0dalirius/goopts.git@latest
go: github.com/p0dalirius/goopts.git@latest: invalid version control suffix in github.com/ path
```

Without the .git in the URL it works but I get an error at the end:

```
$ go install github.com/p0dalirius/goopts@latest
go: downloading github.com/p0dalirius/goopts v1.0.0
go: github.com/p0dalirius/goopts@latest: module github.com/p0dalirius/goopts@latest found (v1.0.0), but does not contain package github.com/p0dalirius/goopts
```

It works perfectly when I `go get github.com/p0dalirius/goopts` in my projects to add it as a dependency though. I will dive into the `go install` command behavior to understand what is happening there.

Best regards,

**Comment by p0dalirius** [comment]
Hi @Muskra,

It seems like there was a misunderstanding regarding the installation command. The `go install` command is intended for installing executable binaries. Since `github.com/p0dalirius/goopts` is a library and does not produce an executable, you won't be able to install it using `go install`.

To use the library in your project, you can add it to your Go module by running:

```
go get github.com/p0dalirius/goopts
```

This command will fetch the library and add it as a dependency in your `go.mod` file.

If you have any further questions or need assistance, feel free to ask!

Best regards,
